### ISSUE TITLE
forceAnnounceNewColumnFamily method removed in cassandra 3.11.6

### ISSUE THREAD

**Issue by miranda-zhang** [Ericsson/ecaudit#137]
The latest version of ecaudit is calling a function removed in Cassandra 3.11.6
`forceAnnounceNewColumnFamily` method was removed in this commit:
https://github.com/apache/cassandra/commit/7e878c1eb61b180227d6f1b70c4223e3ee71a754#diff-504797427c366959087cac83499e5bc5L340

It is still used on this line:
https://github.com/Ericsson/ecaudit/blob/master/ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistDataAccess.java#L235

Possible fix for this line
`MigrationManager.announceNewColumnFamily(expectedTable, false);`

**Comment by eperott** [comment]
Thanks for the report. I am on vaccination and won't be able to look into this until next week.

Don't hesitate to create a pull request if you believe your fix is accurate.

**Comment by eperott** [comment]
This seem to be a problem with 3.0.20 as well in the release/c3.0 branch.

I'm not sure the proposed fix will cover all scenarios. I'll need some time to better understand the details of the MigrationManager.

In any case we should try to come up with a solution which is compatible with previous versions of Cassandra - if possible.

**Comment by eperott** [comment]
The fix will be a little more involved as we need to ensure that the timestamp of the internal tables are 0 (or at least the same every time) to avoid schema miss-match. The resent API changes doesn't really allow the ecAudit plug-in to do that, but I'm working on a solution that will call private methods in the MigrationManager using reflection.

**Comment by eperott** [comment]
Backwards compatible fix is merged into all relevant branches (flavors).

Plan to create new release this week, but want to merge a couple of other improvements first.
