### ISSUE TITLE
Add a wrapping audit authenticator that support custom IAuthenticator implementations

### ISSUE THREAD

**Issue by tobier** [Ericsson/ecaudit#146]
As it is now ecAudit implements an [AuditPasswordAuthenticator](https://github.com/Ericsson/ecaudit/blob/release/c2.2/ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditPasswordAuthenticator.java) that wraps the default PasswordAuthenticator. This makes it difficult to use a custom authenticator together with ecAudit since the underlying authentication mechanism is forced to be the PasswordAuthenticator.

A proprosed solution for this is to use a "wrapped" authenticator that does audit logging based on a wrapped "AuditAuthenticator".

![image](https://user-images.githubusercontent.com/162911/75875863-ce329600-5e14-11ea-8820-c72c53e05efb.png)

The wrapped authenticator would be the authenticator configured in the `cassandra.yaml` and would be similar in implementation to the existing AuditPasswordAuthenticator, but it would direct all calls to the AuditAuthenticator and would also call it to get fields to populate the audit logs with. This would help enable what was discussed in #143 without exposing ecAudit internals. The figure above shows how this is realized with a custom authenticator using the underlying PasswordAuthenticator.

**Comment by tobier** [comment]
@eperott Let's keep the design discussion here for visibility, any comments on this so far?

**Comment by eperott** [comment]
LGTM. Thanks for elaborating on the details.

**Comment by tobier** [comment]
After some thoughts on this, the entire "knowledge" about the authentication session is located in each instantiated SaslNegotiator, so what we should do is to move the `getUser()` and any other fields to new `AuditedSaslNegotiator` returned by a method in the `AuditAuthenticator` interface. The `WrappingAuditLogger` will still do all the audit logging, but using the `AuditedSaslNegotiator` instead.

![image](https://user-images.githubusercontent.com/162911/75987419-30ac9480-5ef0-11ea-94aa-9bffef21ad56.png)

This image illustrates how this could be done with a custom authenticator and Sasl negotiator.
