### ISSUE TITLE
Release plan for 4.0 support

### ISSUE THREAD

**Issue by eperott** [Ericsson/ecaudit#192]
Since 4.0 support is in master branch now, I figured we should discuss a release plan for it.

@tommystendahl, I would like to hear your thoughts on this? Should we just put it out there, or start with a alpha/beta version first?

**Comment by tommystendahl** [comment]
I don't think we need a alpha/beta version, I have tested it for a few weeks now and feel confident with it now so I'm ok with just releasing it.

**Comment by eperott** [comment]
Got it!

Version 2.9.0 should be available on Maven Central in a short while.
