### ISSUE TITLE
Attempt Failed after whitelisting system.peers_v2.

### ISSUE THREAD

**Issue by dhananuttu** [Ericsson/ecaudit#197]
Hi,
Tested version 2.9.1 with latest cassandra 3.11 and get the following error:

{"version":"1.0.0","timestamp":"2022-10-06T09:42:15.069Z","severity":"info","facility":"log audit","message":"SELECT * FROM system.peers_v2","resp_message":"ATTEMPT"}
{"version":"1.0.0","timestamp":"2022-10-06T09:42:15.069Z","severity":"info","message":"SELECT * FROM system.peers_v2","resp_message":"FAILED"}

**Comment by tommystendahl** [comment]
After whitelisting something the cache in ecAudit has to be refreshed before the whitelisting take effect.
