### ISSUE TITLE
ALTER KEYSPACE statement is treated as unrecognized CQLStatement in audit mapping

### ISSUE THREAD

**Issue by FO-H** [Ericsson/ecaudit#198]
Hi,

Found a bug which ALTER KEYSPACE statement is treated as unrecognized CQLStatement in audit mapping.

I tried to run below statement in cqlsh:
ALTER KEYSPACE system_traces WITH replication = {'class': 'NetworkTopologyStrategy', 'dc2': '2', 'dc1': '2'}  AND durable_writes = true;

and i got a warn msg in cassandra log:
[Native-Transport-Requests-1] [com.ericsson.bss.cassandra.ecaudit.entry.factory.AuditEntryBuilderFactory] Detected unrecognized CQLStatement in audit mapping"

**Comment by tommystendahl** [comment]
I think this is limited to the release for Cassandra 4.0. In AuditEntryBuilderFactory.createEntryBuilder(Raw parsedStatement) we have lost the check to see if the statement is a altering schema statement.
