### ISSUE TITLE
Handle values that has not been assigned a value with prepared statements

### ISSUE THREAD

**Issue by tommystendahl** [Ericsson/ecaudit#202]
If a collection has not been assigned a value in a prepared statement ecAudit throws an exception when creating the audit log.

**Comment by WentingWu666666** [comment]
Hi @tommystendahl, we got the following exception recently. Is it the same issue as this one ?

java.nio.BufferUnderflowException: null\\n\",\"\\tat java.nio.Buffer.nextGetIndex(Buffer.java:510)\\n\",\"\\tat java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:375)\\n\",\"\\tat org.apache.cassandra.serializers.CollectionSerializer.readCollectionSize(CollectionSerializer.java:79)\\n\",\"\\tat org.apache.cassandra.cql3.CQL3Type$Collection.toCQLLiteral(CQL3Type.java:194)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.entry.CqlLiteralFlavorAdapter.toCQLLiteral(CqlLiteralFlavorAdapter.java:38)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.entry.PreparedAuditOperation.lambda$preparedWithValues$0(PreparedAuditOperation.java:97)\\n\",\"\\tat java.util.Optional.orElseGet(Optional.java:267)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.entry.PreparedAuditOperation.preparedWithValues(PreparedAuditOperation.java:97)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.entry.PreparedAuditOperation.bindValues(PreparedAuditOperation.java:83)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.entry.PreparedAuditOperation.getOperationString(PreparedAuditOperation.java:65)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.logger.Slf4jAuditLogger.lambda$getAvailableFieldFunctionMap$4(Slf4jAuditLogger.java:101)\\n\",\"\\tat java.util.function.Function.lambda$andThen$1(Function.java:88)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.common.formatter.LogMessageFormatter.lambda$getArgumentsForEntry$1(LogMessageFormatter.java:117)\\n\",\"\\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\\n\",\"\\tat java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)\\n\",\"\\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)\\n\",\"\\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)\\n\",\"\\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)\\n\",\"\\tat java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)\\n\",\"\\tat java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.common.formatter.LogMessageFormatter.getArgumentsForEntry(LogMessageFormatter.java:118)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.logger.Slf4jAuditLogger.log(Slf4jAuditLogger.java:129)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.lambda$performAudit$0(DefaultAuditor.java:104)\\n\",\"\\tat java.util.ArrayList.forEach(ArrayList.java:1259)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.performAudit(DefaultAuditor.java:104)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.audit(DefaultAuditor.java:76)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.AuditAdapter.auditPrepared(AuditAdapter.java:134)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.handler.AuditQueryHandler.processPreparedWithAudit(AuditQueryHandler.java:152)\\n\",\"\\tat com.ericsson.bss.cassandra.ecaudit.handler.AuditQueryHandler.processPrepared(AuditQueryHandler.java:138)\\n\",\"\\tat org.apache.cassandra.transport.messages.ExecuteMessage.execute(ExecuteMessage.java:163)\\n\",\"\\tat org.apache.cassandra.transport.Message$Dispatcher.processRequest(Message.java:688)\\n\",\"\\tat org.apache.cassandra.transport.Message$Dispatcher.lambda$channelRead0$0(Message.java:594)\\n\",\"\\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\\n\",\"\\tat org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162)\\n\",\"\\tat org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113)\\n\",\"\\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\\n\",\"\\tat java.lang.Thread.run(Thread.java:750)\\n\"]"

**Comment by tommystendahl** [comment]
Yes, it looks like you manage to trigger this issue. ecAudit should really log this correctly but if you avoid having values for your prepared statements unassigned you can avoid triggering this, and since its not a good practice to have unassigned values for prepared statements I would recommend that you look into that anyway.
I think we will have an improvement for this in the next release.
