### ISSUE TITLE
Adopt Secure Software Development Best Practices of OpenSSF Scorecard

### ISSUE THREAD

**Issue by gkunz** [Ericsson/ecaudit#246]
I'd like to propose to evaluate and (selectively) adopt secure software development best practices recommended by the Open Source Security Foundation (OpenSSF) [1]. The OpenSSF Scorecard project checks various development best practices of open source projects hosted on GitHub and provides guidance on how to improve those practices [2]. The overall goal of this issue is to adopt best practices to further mature the project.

The proposed steps include:

-  running Scorecards against the ecchronos repo,
-  evaluation of the scan results of Scorecards in terms of applicability,
-  adoption and/or implementation of the recommendation considered feasible and valuable.

[1] https://openssf.org/
[2] https://github.com/ossf/scorecard/tree/main#scorecard-checks

**Comment by gkunz** [comment]
Below is a scan result of the current state of the repo:

Low hanging fruits seem to be

- addition of a SECURITY.MD file,
- configuration of GITHUB_TOKEN permissions,
- branch protection settings

Results:

    {
      "date": "2023-10-30T13:37:02+01:00",
      "repo": {
        "name": "github.com/Ericsson/ecaudit",
        "commit": "a9c46c6f16017ba90206dedd8f87efefce99f495"
      },
      "scorecard": {
        "version": "(devel)",
        "commit": "unknown"
      },
      "score": 5.5,
      "checks": [
        {
          "details": null,
          "score": 10,
          "reason": "no binaries found in the repo",
          "name": "Binary-Artifacts",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#binary-artifacts",
            "short": "Determines if the project has generated executable (binary) artifacts in the source repository."
          }
        },
        {
          "details": [
            "Info: 'force pushes' disabled on branch 'release/c3.11'",
            "Info: 'allow deletion' disabled on branch 'release/c3.11'",
            "Info: status checks require up-to-date branches for 'release/c3.11'",
            "Warn: 'last push approval' disabled on branch 'release/c3.11'",
            "Info: status check found to merge onto on branch 'release/c3.11'",
            "Warn: number of required reviewers is only 1 on branch 'release/c3.11'",
            "Warn: stale review dismissal disabled on branch 'release/c3.11'",
            "Warn: settings do not apply to administrators on branch 'release/c3.11'",
            "Warn: codeowner review is not required on branch 'release/c3.11'"
          ],
          "score": 5,
          "reason": "branch protection is not maximal on development and all release branches",
          "name": "Branch-Protection",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection",
            "short": "Determines if the default and release branches are protected with GitHub's branch protection settings."
          }
        },
        {
          "details": null,
          "score": 10,
          "reason": "11 out of 11 merged PRs checked by a CI test -- score normalized to 10",
          "name": "CI-Tests",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#ci-tests",
            "short": "Determines if the project runs tests before pull requests are merged."
          }
        },
        {
          "details": null,
          "score": 0,
          "reason": "no effort to earn an OpenSSF best practices badge detected",
          "name": "CII-Best-Practices",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#cii-best-practices",
            "short": "Determines if the project has an OpenSSF (formerly CII) Best Practices Badge."
          }
        },
        {
          "details": null,
          "score": 3,
          "reason": "found 19 unreviewed changesets out of 30 -- score normalized to 3",
          "name": "Code-Review",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#code-review",
            "short": "Determines if the project requires human code review before pull requests (aka merge requests) are merged."
          }
        },
        {
          "details": [
            "Info: contributors work for ericsson,lysa"
          ],
          "score": 6,
          "reason": "2 different organizations found -- score normalized to 6",
          "name": "Contributors",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#contributors",
            "short": "Determines if the project has a set of contributors from multiple organizations (e.g., companies)."
          }
        },
        {
          "details": null,
          "score": 10,
          "reason": "no dangerous workflow patterns detected",
          "name": "Dangerous-Workflow",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#dangerous-workflow",
            "short": "Determines if the project's GitHub Action workflows avoid dangerous patterns."
          }
        },
        {
          "details": [
            "Info: tool 'Dependabot' is used: :0"
          ],
          "score": 10,
          "reason": "update tool detected",
          "name": "Dependency-Update-Tool",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool",
            "short": "Determines if the project uses a dependency update tool."
          }
        },
        {
          "details": [
            "Warn: no OSSFuzz integration found: Follow the steps in https://github.com/google/oss-fuzz to integrate fuzzing for your project.\nOver time, try to add fuzzing for more functionalities of your project. (High effort)",
            "Warn: no OneFuzz integration found: Follow the steps in https://github.com/microsoft/onefuzz to start fuzzing for your project.\nOver time, try to add fuzzing for more functionalities of your project. (High effort)",
            "Warn: no GoBuiltInFuzzer integration found: Follow the steps in https://go.dev/doc/fuzz/ to enable fuzzing on your project.\nOver time, try to add fuzzing for more functionalities of your project. (Medium effort)",
            "Warn: no ClusterFuzzLite integration found: Follow the steps in https://github.com/google/clusterfuzzlite to integrate fuzzing as part of CI.\nOver time, try to add fuzzing for more functionalities of your project. (High effort)",
            "Warn: no HaskellPropertyBasedTesting integration found: Use one of the following frameworks to fuzz your project:\nQuickCheck: https://hackage.haskell.org/package/QuickCheck\nhedgehog: https://hedgehog.qa/\nvalidity: https://github.com/NorfairKing/validity\nsmallcheck: https://hackage.haskell.org/package/smallcheck\nhspec: https://hspec.github.io/\ntasty: https://hackage.haskell.org/package/tasty (High effort)",
            "Warn: no TypeScriptPropertyBasedTesting integration found: Use fast-check: https://github.com/dubzzz/fast-check (High effort)",
            "Warn: no JavaScriptPropertyBasedTesting integration found: Use fast-check: https://github.com/dubzzz/fast-check (High effort)"
          ],
          "score": 0,
          "reason": "project is not fuzzed",
          "name": "Fuzzing",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#fuzzing",
            "short": "Determines if the project uses fuzzing."
          }
        },
        {
          "details": [
            "Info: License file found in expected location: LICENSE:1",
            "Info: FSF or OSI recognized license: LICENSE:1"
          ],
          "score": 10,
          "reason": "license file detected",
          "name": "License",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#license",
            "short": "Determines if the project has defined a license."
          }
        },
        {
          "details": null,
          "score": 10,
          "reason": "11 commit(s) out of 30 and 10 issue activity out of 30 found in the last 90 days -- score normalized to 10",
          "name": "Maintained",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained",
            "short": "Determines if the project is \"actively maintained\"."
          }
        },
        {
          "details": [
            "Warn: no GitHub/GitLab publishing workflow detected"
          ],
          "score": -1,
          "reason": "no published package detected",
          "name": "Packaging",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#packaging",
            "short": "Determines if the project is published as a package that others can easily download, install, easily update, and uninstall."
          }
        },
        {
          "details": [
            "Warn: GitHub-owned GitHubAction not pinned by hash: .github/workflows/test.yml:10: update your workflow using https://app.stepsecurity.io/secureworkflow/Ericsson/ecaudit/test.yml/release/c3.11?enable=pin",
            "Warn: GitHub-owned GitHubAction not pinned by hash: .github/workflows/test.yml:12: update your workflow using https://app.stepsecurity.io/secureworkflow/Ericsson/ecaudit/test.yml/release/c3.11?enable=pin",
            "Warn: GitHub-owned GitHubAction not pinned by hash: .github/workflows/test.yml:17: update your workflow using https://app.stepsecurity.io/secureworkflow/Ericsson/ecaudit/test.yml/release/c3.11?enable=pin",
            "Warn: GitHub-owned GitHubAction not pinned by hash: .github/workflows/test.yml:28: update your workflow using https://app.stepsecurity.io/secureworkflow/Ericsson/ecaudit/test.yml/release/c3.11?enable=pin",
            "Warn: GitHub-owned GitHubAction not pinned by hash: .github/workflows/test.yml:30: update your workflow using https://app.stepsecurity.io/secureworkflow/Ericsson/ecaudit/test.yml/release/c3.11?enable=pin",
            "Warn: GitHub-owned GitHubAction not pinned by hash: .github/workflows/test.yml:35: update your workflow using https://app.stepsecurity.io/secureworkflow/Ericsson/ecaudit/test.yml/release/c3.11?enable=pin",
            "Warn: third-party GitHubAction not pinned by hash: .github/workflows/test.yml:43: update your workflow using https://app.stepsecurity.io/secureworkflow/Ericsson/ecaudit/test.yml/release/c3.11?enable=pin",
            "Warn: GitHub-owned GitHubAction not pinned by hash: .github/workflows/test.yml:53: update your workflow using https://app.stepsecurity.io/secureworkflow/Ericsson/ecaudit/test.yml/release/c3.11?enable=pin",
            "Warn: GitHub-owned GitHubAction not pinned by hash: .github/workflows/test.yml:55: update your workflow using https://app.stepsecurity.io/secureworkflow/Ericsson/ecaudit/test.yml/release/c3.11?enable=pin",
            "Warn: GitHub-owned GitHubAction not pinned by hash: .github/workflows/test.yml:60: update your workflow using https://app.stepsecurity.io/secureworkflow/Ericsson/ecaudit/test.yml/release/c3.11?enable=pin",
            "Info:   0 out of   9 GitHub-owned GitHubAction dependencies pinned",
            "Info:   0 out of   1 third-party GitHubAction dependencies pinned"
          ],
          "score": 0,
          "reason": "dependency not pinned by hash detected -- score normalized to 0",
          "name": "Pinned-Dependencies",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies",
            "short": "Determines if the project has declared and pinned the dependencies of its build process."
          }
        },
        {
          "details": [
            "Warn: 0 commits out of 11 are checked with a SAST tool",
            "Warn: CodeQL tool not detected"
          ],
          "score": 0,
          "reason": "SAST tool is not run on all commits -- score normalized to 0",
          "name": "SAST",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#sast",
            "short": "Determines if the project uses static code analysis."
          }
        },
        {
          "details": [
            "Warn: no security policy file detected: On GitHub:\nEnable private vulnerability disclosure in your repository settings https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository\nAdd a section in your SECURITY.md indicating you have enabled private reporting, and tell them to follow the steps in https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability to report vulnerabilities.\nOn GitLab:\nAdd a section in your SECURITY.md indicating the process to disclose vulnerabilities for your project.\nExamples: https://github.com/ossf/scorecard/blob/main/SECURITY.md, https://github.com/slsa-framework/slsa-github-generator/blob/main/SECURITY.md, https://github.com/sigstore/.github/blob/main/SECURITY.md.\nFor additional information on vulnerability disclosure, see https://github.com/ossf/oss-vulnerability-guide/blob/main/maintainer-guide.md. (Medium effort)",
            "Warn: no security file to analyze: On GitHub:\nEnable private vulnerability disclosure in your repository settings https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository\nAdd a section in your SECURITY.md indicating you have enabled private reporting, and tell them to follow the steps in https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability to report vulnerabilities.\nOn GitLab:\nProvide a point of contact in your SECURITY.md.\nExamples: https://github.com/ossf/scorecard/blob/main/SECURITY.md, https://github.com/slsa-framework/slsa-github-generator/blob/main/SECURITY.md, https://github.com/sigstore/.github/blob/main/SECURITY.md. (Low effort)",
            "Warn: no security file to analyze: On GitHub:\nEnable private vulnerability disclosure in your repository settings https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository\nAdd a section in your SECURITY.md indicating you have enabled private reporting, and tell them to follow the steps in https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability to report vulnerabilities.\nOn GitLab:\nAdd a section in your SECURITY.md indicating the process to disclose vulnerabilities for your project.\nExamples: https://github.com/ossf/scorecard/blob/main/SECURITY.md, https://github.com/slsa-framework/slsa-github-generator/blob/main/SECURITY.md, https://github.com/sigstore/.github/blob/main/SECURITY.md. (Low effort)",
            "Warn: no security file to analyze: On GitHub:\nEnable private vulnerability disclosure in your repository settings https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository\nAdd a section in your SECURITY.md indicating you have enabled private reporting, and tell them to follow the steps in https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability to report vulnerabilities.\nOn GitLab:\nAdd a section in your SECURITY.md indicating the process to disclose vulnerabilities for your project.\nExamples: https://github.com/ossf/scorecard/blob/main/SECURITY.md, https://github.com/slsa-framework/slsa-github-generator/blob/main/SECURITY.md, https://github.com/sigstore/.github/blob/main/SECURITY.md. (Low effort)"
          ],
          "score": 0,
          "reason": "security policy file not detected",
          "name": "Security-Policy",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#security-policy",
            "short": "Determines if the project has published a security policy."
          }
        },
        {
          "details": [
            "Warn: no GitHub releases found"
          ],
          "score": -1,
          "reason": "no releases found",
          "name": "Signed-Releases",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#signed-releases",
            "short": "Determines if the project cryptographically signs release artifacts."
          }
        },
        {
          "details": [
            "Warn: no topLevel permission defined: .github/workflows/test.yml:1: Visit https://app.stepsecurity.io/secureworkflow/Ericsson/ecaudit/test.yml/release/c3.11?enable=permissions\nTick the 'Restrict permissions for GITHUB_TOKEN'\nUntick other options\nNOTE: If you want to resolve multiple issues at once, you can visit https://app.stepsecurity.io/securerepo instead. (Low effort)",
            "Info: no jobLevel write permissions found"
          ],
          "score": 0,
          "reason": "detected GitHub workflow tokens with excessive permissions",
          "name": "Token-Permissions",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions",
            "short": "Determines if the project's workflows follow the principle of least privilege."
          }
        },
        {
          "details": [
            "Warn: Project is vulnerable to: GHSA-mjmj-j48q-9wg2",
            "Warn: Project is vulnerable to: GHSA-m9p2-j4hg-g373"
          ],
          "score": 8,
          "reason": "2 existing vulnerabilities detected",
          "name": "Vulnerabilities",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#vulnerabilities",
            "short": "Determines if the project has open, known unfixed vulnerabilities."
          }
        }
      ],
      "metadata": null
    }

**Comment by tommystendahl** [comment]
@gkunz For the GITHUB_TOKEN permissions, is it enough to change the setting to "Workflows have read permissions in the repository for the contents and packages scopes only." or do I need to update in the workflow file also?

**Comment by gkunz** [comment]
@tommystendahl: in principle, you would add a default read permission to the workflow file, similar to what we have done in this PR [1]. Looking at the workflow you have defined, it seems that there is no need for any workflow to write to anything hosted on GitHub, i.e., for which the GITHUB_TOKEN would require write permissions (such as creating releases, issues, etc.). I hope my understanding is correct.

[1] https://github.com/Ericsson/codechecker/pull/3983

**Comment by gkunz** [comment]
Quick status update. After adopting most of the recommendations, the score is up to 7.7

    {
      "date": "2023-11-29T19:24:47+01:00",
      "repo": {
        "name": "github.com/Ericsson/ecaudit",
        "commit": "2f4d962dcac274adb5f82e287098328ff072d759"
      },
      "scorecard": {
        "version": "(devel)",
        "commit": "unknown"
      },
      "score": 7.7,
      "checks": [
        {
          "details": null,
          "score": 10,
          "reason": "no binaries found in the repo",
          "name": "Binary-Artifacts",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#binary-artifacts",
            "short": "Determines if the project has generated executable (binary) artifacts in the source repository."
          }
        },
        {
          "details": [
            "Info: 'force pushes' disabled on branch 'release/c3.11'",
            "Info: 'allow deletion' disabled on branch 'release/c3.11'",
            "Info: status checks require up-to-date branches for 'release/c3.11'",
            "Info: 'last push approval' enabled on branch 'release/c3.11'",
            "Info: status check found to merge onto on branch 'release/c3.11'",
            "Warn: number of required reviewers is only 1 on branch 'release/c3.11'",
            "Info: stale review dismissal enabled on branch 'release/c3.11'",
            "Warn: settings do not apply to administrators on branch 'release/c3.11'",
            "Warn: codeowner review is not required on branch 'release/c3.11'"
          ],
          "score": 8,
          "reason": "branch protection is not maximal on development and all release branches",
          "name": "Branch-Protection",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection",
            "short": "Determines if the default and release branches are protected with GitHub's branch protection settings."
          }
        },
        {
          "details": null,
          "score": 10,
          "reason": "14 out of 14 merged PRs checked by a CI test -- score normalized to 10",
          "name": "CI-Tests",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#ci-tests",
            "short": "Determines if the project runs tests before pull requests are merged."
          }
        },
        {
          "details": null,
          "score": 0,
          "reason": "no effort to earn an OpenSSF best practices badge detected",
          "name": "CII-Best-Practices",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#cii-best-practices",
            "short": "Determines if the project has an OpenSSF (formerly CII) Best Practices Badge."
          }
        },
        {
          "details": null,
          "score": 4,
          "reason": "found 15 unreviewed changesets out of 29 -- score normalized to 4",
          "name": "Code-Review",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#code-review",
            "short": "Determines if the project requires human code review before pull requests (aka merge requests) are merged."
          }
        },
        {
          "details": [
            "Info: contributors work for ericsson,lysa"
          ],
          "score": 6,
          "reason": "2 different organizations found -- score normalized to 6",
          "name": "Contributors",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#contributors",
            "short": "Determines if the project has a set of contributors from multiple organizations (e.g., companies)."
          }
        },
        {
          "details": null,
          "score": 10,
          "reason": "no dangerous workflow patterns detected",
          "name": "Dangerous-Workflow",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#dangerous-workflow",
            "short": "Determines if the project's GitHub Action workflows avoid dangerous patterns."
          }
        },
        {
          "details": [
            "Info: tool 'Dependabot' is used: :0"
          ],
          "score": 10,
          "reason": "update tool detected",
          "name": "Dependency-Update-Tool",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool",
            "short": "Determines if the project uses a dependency update tool."
          }
        },
        {
          "details": [
            "Warn: no OSSFuzz integration found: Follow the steps in https://github.com/google/oss-fuzz to integrate fuzzing for your project.\nOver time, try to add fuzzing for more functionalities of your project. (High effort)",
            "Warn: no OneFuzz integration found: Follow the steps in https://github.com/microsoft/onefuzz to start fuzzing for your project.\nOver time, try to add fuzzing for more functionalities of your project. (High effort)",
            "Warn: no GoBuiltInFuzzer integration found: Follow the steps in https://go.dev/doc/fuzz/ to enable fuzzing on your project.\nOver time, try to add fuzzing for more functionalities of your project. (Medium effort)",
            "Warn: no ClusterFuzzLite integration found: Follow the steps in https://github.com/google/clusterfuzzlite to integrate fuzzing as part of CI.\nOver time, try to add fuzzing for more functionalities of your project. (High effort)",
            "Warn: no HaskellPropertyBasedTesting integration found: Use one of the following frameworks to fuzz your project:\nQuickCheck: https://hackage.haskell.org/package/QuickCheck\nhedgehog: https://hedgehog.qa/\nvalidity: https://github.com/NorfairKing/validity\nsmallcheck: https://hackage.haskell.org/package/smallcheck\nhspec: https://hspec.github.io/\ntasty: https://hackage.haskell.org/package/tasty (High effort)",
            "Warn: no TypeScriptPropertyBasedTesting integration found: Use fast-check: https://github.com/dubzzz/fast-check (High effort)",
            "Warn: no JavaScriptPropertyBasedTesting integration found: Use fast-check: https://github.com/dubzzz/fast-check (High effort)"
          ],
          "score": 0,
          "reason": "project is not fuzzed",
          "name": "Fuzzing",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#fuzzing",
            "short": "Determines if the project uses fuzzing."
          }
        },
        {
          "details": [
            "Info: License file found in expected location: LICENSE:1",
            "Info: FSF or OSI recognized license: LICENSE:1"
          ],
          "score": 10,
          "reason": "license file detected",
          "name": "License",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#license",
            "short": "Determines if the project has defined a license."
          }
        },
        {
          "details": null,
          "score": 10,
          "reason": "23 commit(s) out of 30 and 7 issue activity out of 30 found in the last 90 days -- score normalized to 10",
          "name": "Maintained",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained",
            "short": "Determines if the project is \"actively maintained\"."
          }
        },
        {
          "details": [
            "Warn: no GitHub/GitLab publishing workflow detected"
          ],
          "score": -1,
          "reason": "no published package detected",
          "name": "Packaging",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#packaging",
            "short": "Determines if the project is published as a package that others can easily download, install, easily update, and uninstall."
          }
        },
        {
          "details": [
            "Info:   9 out of   9 GitHub-owned GitHubAction dependencies pinned",
            "Info:   1 out of   1 third-party GitHubAction dependencies pinned"
          ],
          "score": 10,
          "reason": "all dependencies are pinned",
          "name": "Pinned-Dependencies",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies",
            "short": "Determines if the project has declared and pinned the dependencies of its build process."
          }
        },
        {
          "details": [
            "Warn: 0 commits out of 15 are checked with a SAST tool",
            "Warn: CodeQL tool not detected"
          ],
          "score": 0,
          "reason": "SAST tool is not run on all commits -- score normalized to 0",
          "name": "SAST",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#sast",
            "short": "Determines if the project uses static code analysis."
          }
        },
        {
          "details": [
            "Info: security policy file detected: SECURITY.md:1",
            "Info: Found linked content: SECURITY.md:1",
            "Info: Found disclosure, vulnerability, and/or timelines in security policy: SECURITY.md:1",
            "Info: Found text in security policy: SECURITY.md:1"
          ],
          "score": 10,
          "reason": "security policy file detected",
          "name": "Security-Policy",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#security-policy",
            "short": "Determines if the project has published a security policy."
          }
        },
        {
          "details": [
            "Warn: no GitHub releases found"
          ],
          "score": -1,
          "reason": "no releases found",
          "name": "Signed-Releases",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#signed-releases",
            "short": "Determines if the project cryptographically signs release artifacts."
          }
        },
        {
          "details": [
            "Info: topLevel permissions set to 'read-all': .github/workflows/test.yml:5",
            "Info: no jobLevel write permissions found"
          ],
          "score": 10,
          "reason": "GitHub workflow tokens follow principle of least privilege",
          "name": "Token-Permissions",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions",
            "short": "Determines if the project's workflows follow the principle of least privilege."
          }
        },
        {
          "details": [
            "Warn: Project is vulnerable to: GHSA-mjmj-j48q-9wg2",
            "Warn: Project is vulnerable to: GHSA-m9p2-j4hg-g373"
          ],
          "score": 8,
          "reason": "2 existing vulnerabilities detected",
          "name": "Vulnerabilities",
          "documentation": {
            "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#vulnerabilities",
            "short": "Determines if the project has open, known unfixed vulnerabilities."
          }
        }
      ],
      "metadata": null
    }

**Comment by tommystendahl** [comment]
I have activated CodeQL also. I think we have done what we can for the moment.

**Comment by gkunz** [comment]
@tommystendahl, thanks for the update and thank you for the effort of adopting the recommendations.

Based on this, we can close this issue.
