### ISSUE TITLE
Only  login "Authentication attempt " operations are logged 

### ISSUE THREAD

**Issue by ashokkoti** [Ericsson/ecaudit#26]
Hi ,

I started to test audit plugin for Cassandra 3.11.2.

Followed the steps as per  https://github.com/Ericsson/ecaudit/blob/release/c3.0/doc/setup.md  .

i was testing from cql.
But only  login "Authentication attempt " operations are logged  .
Select ,insert,delete and other operations are not logged in the audit log file .

Is there any extra steps needed be done 

Testing:

[cassandra@xxxxxxxxxxxx:/opt/app/cassandra/conf]$ cqlsh `hostname` -u coach -p 'All4One2day!'
Connected to xxx-cluster at xxxxxxxxxx:9042.
[cqlsh 5.0.1 | Cassandra 3.11.2 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
coach@cqlsh> INSERT INTO cycling.cyclist_name (id, lastname, firstname) VALUES (5b6962dd-3f90-4c93-8f61-eabfa4a803d4, 'VOSAA','Marianneee');
coach@cqlsh>
coach@cqlsh> select * from  cycling.cyclist_name;

 id                                   | firstname  | lastname
--------------------------------------+------------+----------
 5b6962dd-3f90-4c93-8f61-eabfa4a803d4 | Marianneee |    VOSAA
 5b6962dd-3f90-4c93-8f61-eabfa4a803e2 |   Marianne |      VOS

(2 rows)
coach@cqlsh>

Checking the audit.log

cassandra@xxxxxxxx:/opt/app/cassandra/logs/audit]$ tail  -100f audit.log
1:23:54.312 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:23:54.629 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:24:48.392 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:24:48.630 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:28:51.354 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:28:51.572 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:29:51.180 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:29:51.647 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:32:41.467 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:32:41.718 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:36:14.425 - client:'xx.xx.xxx.xx'|user:'coach'|status:'ATTEMPT'|operation:'Authentication attempt'
1:36:14.603 - client:'xx.xx.xxx.xx'|user:'coach'|status:'ATTEMPT'|operation:'Authentication attempt'
1:37:01.494 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:37:01.715 - client:'xx.xx.xxx.xx'|user:'cassandra'|status:'ATTEMPT'|operation:'Authentication attempt'
1:44:56.526 - client:'xx.xx.xxx.xx'|user:'coach'|status:'ATTEMPT'|operation:'Authentication attempt'
1:44:56.834 - client:'xx.xx.xxx.xx'|user:'coach'|status:'ATTEMPT'|operation:'Authentication attempt'

**Comment by ashokkoti** [comment]
Hi @eperott 

Thanks for quick reply .

 JVM_EXTRA_OPTS  was set in cassandra-env.sh  and AFAIK we are not using any  custom query handler.


[cassandra@xxx.xx.xx.xxx:/opt/app/cassandra/conf]$ tail -5f cassandra-env.sh

JVM_OPTS="$JVM_OPTS $MX4J_ADDRESS"
JVM_OPTS="$JVM_OPTS $MX4J_PORT"
JVM_OPTS="$JVM_OPTS $JVM_EXTRA_OPTS"
JVM_EXTRA_OPTS="$JVM_EXTRA_OPTS -Dcassandra.custom_query_handler_class=com.ericsson.bss.cassandra.ecaudit.handler.AuditQueryHandler"



Few lines from system.log 
--------------

INFO  [main] 2018-10-02 14:02:02,573 GossipingPropertyFileSnitch.java:64 - Loaded cassandra-topology.properties for compatibility
INFO  [main] 2018-10-02 14:02:02,612 AuditAdapterFactory.java:91 - Audit whitelist from ROLE options
INFO  [main] 2018-10-02 14:02:02,617 AuditPasswordAuthenticator.java:59 - Auditing enabled on authenticator
INFO  [main] 2018-10-02 14:02:02,622 AuditRoleManager.java:57 - Auditing enabled on role manager
INFO  [main] 2018-10-02 14:02:02,660 JMXServerUtils.java:246 - Configured JMX server at: service:jmx:rmi://127.0.0.1/jndi/rmi://127.0.0.1:7199/jmxrmi

**Comment by ashokkoti** [comment]
Hi @eperott 

Thanks  for solution .Its working 

Changed "JVM_OPTS="$JVM_OPTS $JVM_EXTRA_OPTS"" to end of file "cassandra-env.sh"


Regards
Ashok

**Comment by eperott** [comment]
Happy to help! :-) Closing ticket.
