### ISSUE TITLE
Question about support for Cassandra 3.11.17

### ISSUE THREAD

**Issue by HarrySadleir** [Ericsson/ecaudit#267]
Hi there. I am currently preparing to upgrade a Cassandra database to version 3.11.17. We use the ecaudit plugin, and so I am wondering about ecaudit's support of this version, [as it is not listed in your compatibility matrix.](https://github.com/Ericsson/ecaudit/blob/release/c3.11/doc/cassandra_compatibility.md). 

Is it known whether ecaudit_c3.11 2.10.0 will work, or whether a new ecaudit version will be necessary? Thanks in advance!

**Comment by tommystendahl** [comment]
Hi,
Thanks for your question. I can confirm that  ecaudit_c3.11 2.10.0 works with Cassandra 3.11.17 and I have updated the compatibility doc accordingly.

**Comment by HarrySadleir** [comment]
Thank you for the information, that is very helpful 😄
