### ISSUE TITLE
Fix default path for audit.yaml

### ISSUE THREAD

**Issue by eperott** [Ericsson/ecaudit#59]
Currently ecAudit is looking for the `audit.yaml` file in `/etc/cassandra/conf/`. It would be nice if ecAudit was looking for `audit.yaml` in the directory specified by the `$CASSANDRA_CONF` environment variable. The `/etc/cassandra/conf/` should still be the fallback if `$CASSANDRA_CONF` is not defined

Finally we should remain backwards compatible with the current option which allows you to configure the path using the Java property named `com.ericsson.bss.cassandra.eaudit.config`. This option takes precedence of `$CASSANDRA_CONF`. BTW, this should be documented.

**Comment by etedpet** [comment]
Also make sure the Java property name is corrected to: com.ericsson.bss.cassandra.**ecaudit**.config

**Comment by eperott** [comment]
Solution proposal:
- If a configuration file is specified with the `com.ericsson.bss.cassandra.ecaudit.config` property, then we expect the file to be there and we use it.
- Otherwise we look for `audit.yaml` in the Cassandra configuration directory and we use it if it is there. If no file is not found at this location we fall back to default config values where it makes sense, otherwise we fail at startup.
- The Cassandra configuration directory will typically be `/etc/cassandra/conf/`, and so we remain backwards compatible.
