### ISSUE TITLE
Unstable Test in ITVerifyThreadedAudit

### ISSUE THREAD

**Issue by etedpet** [Ericsson/ecaudit#63]
ITVerifyThreadedAudit.testValidPreparedStatementsAreLogged sometimes fails on Travis CI.
Test/code must be updated to get a predictable test result.

**Comment by etedpet** [comment]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 51.457 s <<< FAILURE! - in com.ericsson.bss.cassandra.ecaudit.integration.ITVerifyThreadedAudit
[ERROR] testValidPreparedStatementsAreLogged(com.ericsson.bss.cassandra.ecaudit.integration.ITVerifyThreadedAudit)  Time elapsed: 20.398 s  <<< ERROR!
java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:51577 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.0.1:51577] Operation timed out))
	at com.ericsson.bss.cassandra.ecaudit.integration.ITVerifyThreadedAudit.testValidPreparedStatementsAreLogged(ITVerifyThreadedAudit.java:152)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:51577 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.0.1:51577] Operation timed out))
...
[ERROR] Errors: 
[ERROR]   ITVerifyThreadedAudit.testValidPreparedStatementsAreLogged:152 » Execution com...
[INFO] 
[ERROR] Tests run: 103, Failures: 0, Errors: 1, Skipped: 0

**Comment by eperott** [comment]
Turns out this issue was triggered by the newly added integration tests for configurable log format. So this is going to be an accelerating problem as we want to have integration tests with different configurations. Would it make sense to create different maven modules for different sets of integration tests?
