### ISSUE TITLE
Use queryStartNanoTime in ecaudit_c3.11

### ISSUE THREAD

**Issue by eperott** [Ericsson/ecaudit#80]
In #27 we introduced support for timestamps generated by ecAudit itself rather than relying on the logger backend to generate one at the time of writing. This improved accuracy a bit.

In ecaudit_c3.0 and ecaudit_c3.0.11 we're generating a timestamp ourself in the plugin; in the ```AuditQueryHandler``` for CQL queries. However, in ecaudit_c3.11 we get a timestamp (named queryStartNanoTime) from Cassandra into the method signatures. We should consider to use it in our audit records rather than generating one on our own.

**Comment by etedpet** [comment]
The queryStartNanoTime variable is used for "other things", see: https://issues.apache.org/jira/browse/CASSANDRA-12256.
It is used for handling/getting correct timeouts for requests.

Also, the timestamp is populated by System.nanoTime(), which is "the current value of the running Java Virtual Machine's high-resolution time source, in nanoseconds"... And is not really comparable to anything other than whats in the current process... Will not be the same on different nodes or after a restart of the JVM.

So we should probably stick to populating out TIMESTAMP-field with the System.currentTimeMillis(), which is "the difference, measured in milliseconds, between the current time and midnight, January 1, 1970 UTC". This is also how timestamps are handled in Cassandra 4.0 audit.
